# Bundled default model build parameters for a DMOTE.
# This is not the full set of available parameters.
# Read the project documentation.

keycaps:
  body-height: 7.3  # DSA-profile caps.
  resting-clearance: 6.5  # DSA on Matias switches.
switches:
  travel: 3.5
key-clusters:
  finger:
    matrix-columns:
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
      rows-below-home: 2
    - rows-above-home: 1
      rows-below-home: 3
    - rows-above-home: 1
      rows-below-home: 2
    - rows-below-home: 2
    - rows-below-home: 2
    aliases:
      f0: [0, first]
      f1: [1, first]
      f2: [2, first]
      back: [1, last]
      far-right: [last, last]
      near-right: [last, first]
  thumb:
    position:
      key-alias: f1
      offset: [-12, -17, 5]
    matrix-columns:
    - rows-above-home: 1
    - rows-above-home: 1
      rows-below-home: 1
    - rows-above-home: 1
    aliases:
      t0: [0, last]
      t1: [1, last]
      t2: [last, last]
      t3: [last, first]
      t4: [1, first]
      t5: [0, first]
by-key:
  parameters:
    channel:
      height: 20
      top-width: 10
      margin: 0.5
    wall:
      thickness: 1
      bevel: 1
      north:
        perpendicular: -8
      east:
        perpendicular: -8
      south:
        perpendicular: -8
      west:
        perpendicular: -8
  clusters:
    finger:
      parameters:
        layout:
          matrix:
            neutral:
              column: 2
            separation:
              row: 0
              column: 0.6
          pitch:
            base: 0.26
            progressive: 0.45
          roll:
            base: 0.22
            progressive: 0.1
          yaw:
            base: 0.03
          translation:
            late: [0, 0, 9]
      columns:
        "0":
          parameters:
            layout:
              matrix:
                separation:
                  row: 0.3
              translation:
                early: [-1, -2, 2]
              roll:
                intrinsic: 0.05
            wall:
              south:
                extent: 3
                perpendicular: 4
          rows:
            last:
              parameters:
                wall:
                  north:
                    extent: 0
        "1":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.8
            wall:
              south:
                extent: 3
                parallel: 3
                perpendicular: 4
              west:
                extent: 3
                parallel: 3
                perpendicular: 4
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.1
                  yaw:
                    intrinsic: -0.05
                  translation:
                    early: [-1, -2, 3]
                channel:
                  top-width: 15
            "0":
              parameters:
                layout:
                  translation:
                    early: [0, 0, -1]
            last:
              parameters:
                wall:
                  north:
                    extent: 0
        "2":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.8
              translation:
                mid: [0, 3, -3]
            wall:
              south:
                extent: 1
              west:
                extent: 0
          rows:
            "-3":
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.2
                  translation:
                    early: [0, -5, 4]
                wall:
                  east:
                    extent: 4
            "-2":
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.1
                  translation:
                    early: [0, -2, 3]
            "0":
              parameters:
                layout:
                  translation:
                    early: [0, 0, -1]
            last:
              parameters:
                wall:
                  north:
                    extent: 0
        "3":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.8
          rows:
            first:
              parameters:
                layout:
                  pitch:
                    intrinsic: -0.1
                  yaw:
                    intrinsic: 0.05
                  translation:
                    early: [1, -2, 3]
            "0":
              parameters:
                layout:
                  translation:
                    early: [0, 0, -1]
            last:
              parameters:
                wall:
                  north:
                    extent: 0
        "4":
          parameters:
            layout:
              matrix:
                separation:
                  row: -0.8
                neutral:
                  row: -1
              pitch:
                base: 0.16
                progressive: 0.6
              roll:
                base: 0.17
              yaw:
                base: 0.07
              translation:
                mid: [1.5, 4, 2]
          rows:
            "-1":
              parameters:
                layout:
                  translation:
                    early: [0, 0, -1]
        "5":
          parameters:
            layout:
              matrix:
                neutral:
                  row: -1
              pitch:
                base: 0.16
                progressive: 0.6
              roll:
                base: 0.17
                intrinsic: -0.15
              yaw:
                base: 0.07
              translation:
                mid: [2.5, 4, 4.5]
    thumb:
      parameters:
        layout:
          matrix:
            neutral:
              column: 1
            separation:
              column: 0.5
          roll:
            base: -1.3
            progressive: 0.3
          pitch:
            base: -0.4
            progressive: 0.3
          yaw:
            base: 1
        wall:
          north:
            extent: 1
          east:
            extent: 4
          south:
            extent: 4
          west:
            extent: 0
      columns:
        "0":
          parameters:
            layout:
              translation:
                mid: [0, -4, 0]
            wall:
              south:
                extent: 1
          rows:
            "0":
              parameters:
                layout:
                  translation:
                    early: [0, -2, 0]
                  pitch:
                    intrinsic: -0.25
            "1":
              parameters:
                layout:
                  translation:
                    early: [-1, 0, 0]
        "1":
          parameters:
            layout:
              translation:
                mid: [0, 3, 0]
            wall:
              north:
                extent: 4
                perpendicular: -4
          rows:
            "-1":
              parameters:
                layout:
                  translation:
                    early: [0, 1, -4]
                wall:
                  east:
                    extent: 1
            "1":
              parameters:
                layout:
                  translation:
                    early: [0, 0, 4]
        "2":
          parameters:
            layout:
              translation:
                mid: [0, -4, 0]
          rows:
            "0":
              parameters:
                layout:
                  translation:
                    early: [0, -2, 0]
                  pitch:
                    intrinsic: -0.25
                wall:
                  south:
                    extent: 1
            "1":
              parameters:
                layout:
                  translation:
                    early: [1, 0, 0]
case:
  key-mount-thickness: 2.5
  web-thickness: 2.5
  rear-housing:
    include: true
    west-foot: true
    distance: 3
    height: 43
    offsets:
      north: 14
      east: -2
    fasteners:
      diameter: 6
      bosses: true
      west:
        include: true
        offset: 0
      east:
        include: true
        offset: -15
  back-plate:
    include: false
    beam-height: 20
    fasteners:
      diameter: 6
      distance: 30
    position:
      key-alias: back
      offset: [0, 0, 0]
  leds:
    include: true
    amount: 3
    # Settings here are for WS2818 diodes at 17 mm intervals.
    housing-size: 5.5  # Real size: 5 mm.
    emitter-diameter: 4
    interval: 16.8
  tweaks:
  # First, a bunch of extra webbing at the four corners of the thumb cluster:
  - hull-around:
    - [t0, NNW, 0, 1]
    - [t0, NNE, 0, 1]
    - [t1, NNW, 0, 1]
  - hull-around:
    - [t2, NNW, 0, 1]
    - [t2, NNE, 0, 1]
    - [t1, NNE, 0, 1]
  - chunk-size: 3
    hull-around:
    - [t4, ENE, 0]
    - hull-around:
      - [t4, ESE, 0, 4]
      - [t4, SSE, 0, 4]
    - hull-around:
      - [t3, WSW, 0, 1]
      - [t3, SSW, 0, 1]
    - hull-around:
      - [t3, SSE, 0, 4]
      - [t3, ESE, 0, 4]
  - chunk-size: 3
    hull-around:
    - [t4, WNW, 0, 1]
    - hull-around:
      - [t5, ESE, 0, 1]
      - [t5, SSE, 0, 1]
    - hull-around:
      - [t4, WSW, 0, 1]
      - [t4, SSW, 0, 1]
    - [t5, SSW, 0, 1]
  # Plating over the cluster gap:
  - chunk-size: 3
    hull-around:
    - [t1, NNW, 3, 4]
    - hull-around:
      - [t1, ENE, 0, 4]
      - [t1, NNE, 0, 4]
    - hull-around:
      - [f0, SSW, 0, 3]
      - [f0, WSW, 0, 3]
    - [t2, NNE, 0, 4]
    - [t2, ENE, 0, 4]
  - chunk-size: 3
    hull-around:
    - [f0, SSW, 0, 3]
    - hull-around:
      - [t2, NNE, 3, 4]
      - [t2, ENE, 3, 4]
    - [f0, SSE, 0, 3]
    - [t2, ESE, 4]
    - hull-around:
      - [f1, WNW, 0, 3]
      - [f1, WSW, 0, 3]
      - [f1, SSW, 0, 2]
    - [t3, ENE, 4]
    - hull-around:
      - [f1, SSE, 2]
      - [f2, NNW, 0]
    - hull-around:
      - [f2, WSW, 0, 1]
      - [f2, SSW, 0, 1]
    - [t3, NNE, 4]
    - [f2, SSW, 1]
    - hull-around:
      - [t3, ESE, 4]
      - [t3, SSE, 4]
    - hull-around:
      - [f2, ESE, 1, 4]
      - [f2, SSE, 1, 4]
    - [t4, ESE, 4]
    - [f2, ENE, 3, 4]
  # A plate to ground beneath the entire thumb cluster:
  - to-ground: true
    chunk-size: 2
    hull-around:
    - [f0, WSW, 2, 3]
    - hull-around:
      - [t1, NNW, 0, 4]
      - [t0, NNE, 0, 1]
      - [t0, NNW, 0, 3]
    - [t0, WNW, 0, 1]
    - [t0, WSW, 0, 1]
    - [t5, WNW, 0, 1]
    - [t5, WSW, 0, 1]
    - [t5, SSW, 0, 1]
    - [t4, SSW, 0, 4]
    - [t4, SSE, 4]
    - [f2, ENE, 3, 4]
  foot-plates:
    include: true
    height: 4
    polygons:
    - points:
      - key-alias: far-right
        key-corner: WNW
        offset: [7, 0]
      - key-alias: far-right
        key-corner: NNE
      - key-alias: far-right
        key-corner: ESE
        offset: [0, -2]
    - points:
      - key-alias: near-right
        key-corner: SSW
        offset: [4, 1]
      - key-alias: near-right
        key-corner: NNE
        offset: [1, -5]
      - key-alias: near-right
        key-corner: ESE
mcu:
  type: promicro
  margin: 0.3
  position:
    prefer-rear-housing: true
    key-alias: back
    corner: ENE
    offset: [-1, 0, 2]
  support:
    style: lock
    height-factor: 0.5
    lateral-spacing: 2.5
    lock:
      fastener:
        style: button
        diameter: 3
      socket:
        thickness: 1.5
      bolt:
        clearance: 2.1
        overshoot: 1
        mount-length: 10
        mount-thickness: 6
    stop:
      key-alias: back
      direction: east
      gripper:
        notch-depth: 0.4
        total-depth: 5
        grip-width: 0.6
connection:
  socket-size: [10, 11, 17.7]  # 616E minus the vertical bar is 10 mm wide.
  position:
    prefer-rear-housing: true
    key-alias: back
    corner: ENE
    raise: true
wrist-rest:
  include: false
  style: threaded
  position:
    key-alias: near-right
    offset: [-40, -50]
  shape:
    plinth-base-size: [66, 80, 42]
    chamfer: 2
    lip-height: 2
    pad:
      surface-heightmap: ../resources/heightmap/default.dat
      height:
        surface-range: 10
        lip-to-surface: 2
        below-lip: 5
